service: Restaurant

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-package-external
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin

package:
  individually: true

custom:
  dotenv:
    path: '../../../.env'
    exclude: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  packageExternal:
    external:
      - '../../config'
  webpack:
    webpackConfig: '../../../webpack.config.js'
  serverless-offline:
    httpPort: 7000

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  Auth:
    handler: libs/auth.authorize
  CreateUser:
    handler: controllers/createUser.handler
    timeout: 30
    events:
      - http:
          path: /user
          method: put
          cors: true
  DeleteUser:
    handler: controllers/deleteUser.handler
    timeout: 30
    events:
      - http:
          path: /user
          method: delete
          cors: true
  SignIn:
    handler: controllers/signIn.handler
    timeout: 30
    events:
      - http:
          path: /user
          method: post
          cors: true
          # authorizer:
          #   resultTtlInSeconds: 0
          #   identitySource: method.request.header.Authorization
          #   name: Auth
