name: Test Restaurant Service server

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.1]

    steps:
      - name: Checking out code from git
        uses: actions/checkout@v2

      - name: User Node.js ${{matrix.node-servsion}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-servsion}}
      - name: Setting environment variables
        run: |
          chmod +x ./scripts/set-env.sh
          ./scripts/set-env.sh
          cat .env

        env:
          PORT: ${{secrets.PORT}}
      
      - run: npm install
      - run: npm test