name: Build docker image and publish on Docker Hub

on: push

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from git
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildX-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Setting environment variables
        run: |
          chmod +x ./src/scripts/set-env.sh
          ./src/scripts/set-env.sh
        env:
          PORT: ${{secrets.PORT}}
        
      - name: Building docker image
        run: make build
      - name: Test docker image
        run: make test
      - name: Publishing docker image to docker hub
        run: make push